language: java
cache:
    directories:
     - "$HOME/.m2/repository"
     - "$HOME/.sonar/cache"

services:
     - docker

jdk:
     - openjdk11


script:
     - cd springboot
     - mvn clean verify
